on: push
jobs:
    build-node:
      runs-on: ubuntu-latest
      container: cassandra
      steps:
        - run: echo "Tarea 8"
        - run: cqlsh localhost
        - run: echo "Proceso terminado"