on: push
jobs:
    build-node:
      runs-on: ubuntu-latest
      container: cassandra
      steps:
        - run: echo "Tarea 8"
        - run: SELECT cql_version FROM system.local
        - run: echo "Proceso terminado"